apiVersion: apps/v1

kind: Deployment

metadata:

  name: webapp7

spec:

  replicas: 3

  selector:

   matchLabels:

    app: webapp7

  template:

    metadata:

      labels:

        app: webapp7

    spec:

      containers:

      - name: webapp7

        image: gcr.io/beaming-courage-261719/kubernetesrepos1:tagversion

        ports:

        - containerPort: 8080

---

apiVersion: v1

kind: Service

metadata:

  name: webapp7-svc

  labels:

    app: webapp7

spec:

  type: LoadBalancer

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8080

  selector:

    app: webapp7
