apiVersion: apps/v1

kind: Deployment

metadata:

  name: webapp6

spec:

  replicas: 3

  selector:

   matchLabels:

    app: webapp6

  template:

    metadata:

      labels:

        app: webapp6

    spec:

      containers:

      - name: webapp6

        image: gcr.io/beaming-courage-261719/kubernetesrepos1:tagversion

        ports:

        - containerPort: 8080

---

apiVersion: v1

kind: Service

metadata:

  name: webapp6-svc

  labels:

    app: webapp6

spec:

  type: LoadBalancer

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8080

  selector:

    app: webapp6
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp6-svc
  labels:
    app: webapp6
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: webapp6 
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 1
  desiredReplicas: 1
